### ISSUE TITLE
Cannot redeclare class Cors

### ISSUE THREAD

**Issue by li0nel** [nordsoftware/lumen-cors#2] opened 2015-06-17 15:16 UTC
In CorsServiceProvider.php
on line 21: class_alias('Nord\Lumen\Cors\CorsFacade', 'Cors');

During PHPUnit tests, this line is called twice and fails on redeclaring class Cors

Any idea?

Thx

**Comment by cniska** [comment] 2015-06-20 22:04
You must have a class called `Cors` in the root namespace. That's the only reason I can think of that could cause that error.

**Comment by catalinux** [comment] 2015-06-29 20:03
The problem is that the application is loaded again to instantiate the Application object. I made some changes: https://github.com/nordsoftware/lumen-cors/commit/9e4f966695fcc18523174632ca21ecc9d762c49d

**Comment by boedy** [comment] 2015-11-20 12:55
temp fix until pull request get's accepted:

``` php
if( ! class_exists('Cors')){
    $app->register('Nord\Lumen\Cors\CorsServiceProvider');
}
```

**Comment by cniska** [comment] 2015-11-21 21:34
That's true, but the proper fix is to wrap registering of the `Cors` alias with a `class_exists('Cors')` check.

**Comment by catalinux** [comment] 2015-11-23 08:25
@crisu83 do you want me to change my pull request https://github.com/nordsoftware/lumen-cors/commit/9e4f966695fcc18523174632ca21ecc9d762c49d ?

**Comment by cniska** [comment] 2015-11-23 09:14
@catalinux Sure.

**Comment by cniska** [comment] 2015-12-23 21:29
I just merged a fix for this.

**Closed as completed by cniska** 2015-12-23 21:29 UTC
