### ISSUE TITLE
Trailing slash redirect causes CORS error

### ISSUE THREAD

**Issue by rohitsodhia** [nordsoftware/lumen-cors#32] opened 2017-03-12 03:32 UTC
### What did you do?

Make a CORS request with a trailing slash

### What did you expect to happen?

Get back data.

### What actually happened?

Get the following error:

`XMLHttpRequest cannot load http://api.site.local/forums/. Redirect from 'http://api.site.local/forums/' to 'http://api.site.local/forums' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'http://site.local' is therefore not allowed access.

### What versions of PHP, Lumen and this module are you using?

PHP 7.1, Lumen 5.3, Nord 1.6

Honestly, this may be more a question than issue, and if so, my apologies. It's quite possible I'm doing something that's erroneous with Lumen or how CORS works. I currently have the config set to `'allow_origins' => ['*'],`, so I don't quite understand why this error is coming up.

I'm trying to access pages with a trailing slash, knowing Lumen will redirect them to the page without the trailing slash, but it breaks the CORS request, and while I'd really like to get trailing slashes working, if they don't work, I'd mostly just like to understand why.

**Comment by Jalle19** [comment] 2017-08-24 10:35
Hard to tell without more information, but I guess the headers disappear when Lumen does a redirect. Why don't you send the request directly to the correct URL and thus avoid the redirect?

**Comment by rohitsodhia** [comment] 2017-08-24 18:28
In general, I do, I was hoping to learn more about how things work, and in general, in the past, I tended to build sites that always had the trailing slash. Obviously, I was going directly to the URL to make my project work.

**Comment by Jalle19** [comment] 2017-08-24 19:16
I doubt it's Lumen that redirects in this case, it's probably your web server. Since you apparently solved this already (sorry for not noticing this issue earlier) I'll close this.

**Closed as completed by Jalle19** 2017-08-24 19:16 UTC
Labels: question

**Comment by rohitsodhia** [comment] 2017-08-24 20:04
Well, it's my understanding that Lumen is the part that does the redirect; from my research, it strips trailing slashes. That's one of the reasons this bug bothered me: if Lumen does the redirect, it'd be nice to get it to work with that piece of functionality.

**Comment by Jalle19** [comment] 2017-08-27 17:59
AFAIK Lumen doesn't do that, but I could be wrong. Normally this type of redirect is done by the web server itself.

**Comment by kingbeto** [comment] 2019-06-15 23:41
This is caused by your .htaccess in /public directory.
These are the guilty lines:
    # Redirect Trailing Slashes If Not A Folder...
    RewriteCond %{REQUEST_FILENAME} !-d
    RewriteCond %{REQUEST_URI} (.+)/$
    RewriteRule ^ %1 [L,R=301]
